{"name": "test_exception2", "status": "passed", "start": 1574158469625, "stop": 1574158472650, "uuid": "57cdcbaa-0a30-4de3-833c-dcae018137e4", "historyId": "588d2b5b14755c82411005d34ffae80c", "testCaseId": "c5600b26744433c105d7636fe31fdc9c", "fullName": "tests.test_1#test_exception2", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_1"}, {"name": "host", "value": "b4d74a60ed0c"}, {"name": "thread", "value": "7-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_1"}]}